//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mhazami.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ProjectsFoundation {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ProjectsFoundation() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Mhazami.Resources.ProjectsFoundation", typeof(ProjectsFoundation).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to August.
        /// </summary>
        public static string Aban {
            get {
                return ResourceManager.GetString("Aban", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ago.
        /// </summary>
        public static string Ago {
            get {
                return ResourceManager.GetString("Ago", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to one hundred.
        /// </summary>
        public static string ahundred {
            get {
                return ResourceManager.GetString("ahundred", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to And.
        /// </summary>
        public static string And {
            get {
                return ResourceManager.GetString("And", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attention.
        /// </summary>
        public static string Attention {
            get {
                return ResourceManager.GetString("Attention", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attention.
        /// </summary>
        public static string Attention1 {
            get {
                return ResourceManager.GetString("Attention1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to September.
        /// </summary>
        public static string Azar {
            get {
                return ResourceManager.GetString("Azar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to November.
        /// </summary>
        public static string Bahman {
            get {
                return ResourceManager.GetString("Bahman", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to billion.
        /// </summary>
        public static string billion {
            get {
                return ResourceManager.GetString("billion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blank.
        /// </summary>
        public static string Blank {
            get {
                return ResourceManager.GetString("Blank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create.
        /// </summary>
        public static string Create {
            get {
                return ResourceManager.GetString("Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data Fetch Failed.
        /// </summary>
        public static string DataFetchFailed {
            get {
                return ResourceManager.GetString("DataFetchFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data Fetch Failed.
        /// </summary>
        public static string DataFetchFailed1 {
            get {
                return ResourceManager.GetString("DataFetchFailed1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Day(s).
        /// </summary>
        public static string Day {
            get {
                return ResourceManager.GetString("Day", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Document.
        /// </summary>
        public static string DeleteDoc {
            get {
                return ResourceManager.GetString("DeleteDoc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Document.
        /// </summary>
        public static string DeleteDoc1 {
            get {
                return ResourceManager.GetString("DeleteDoc1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to delete the following information?.
        /// </summary>
        public static string DeleteMessage {
            get {
                return ResourceManager.GetString("DeleteMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Record.
        /// </summary>
        public static string DeleteRecord {
            get {
                return ResourceManager.GetString("DeleteRecord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Record.
        /// </summary>
        public static string DeleteRecord1 {
            get {
                return ResourceManager.GetString("DeleteRecord1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Information deleted successfully..
        /// </summary>
        public static string DeleteSuccessMessage {
            get {
                return ResourceManager.GetString("DeleteSuccessMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleting Data Failed.
        /// </summary>
        public static string DeletingDataFailed {
            get {
                return ResourceManager.GetString("DeletingDataFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleting Data Failed.
        /// </summary>
        public static string DeletingDataFailed1 {
            get {
                return ResourceManager.GetString("DeletingDataFailed1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Details.
        /// </summary>
        public static string Details {
            get {
                return ResourceManager.GetString("Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Details.
        /// </summary>
        public static string Details1 {
            get {
                return ResourceManager.GetString("Details1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to October.
        /// </summary>
        public static string Dey {
            get {
                return ResourceManager.GetString("Dey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ltr.
        /// </summary>
        public static string Direction {
            get {
                return ResourceManager.GetString("Direction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ltr.
        /// </summary>
        public static string Direction1 {
            get {
                return ResourceManager.GetString("Direction1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inactive.
        /// </summary>
        public static string Disable {
            get {
                return ResourceManager.GetString("Disable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The desired conference is disabled at this address.
        /// </summary>
        public static string Disabled {
            get {
                return ResourceManager.GetString("Disabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duplicated.
        /// </summary>
        public static string Duplicated {
            get {
                return ResourceManager.GetString("Duplicated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duplicated.
        /// </summary>
        public static string Duplicated1 {
            get {
                return ResourceManager.GetString("Duplicated1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to eight.
        /// </summary>
        public static string eight {
            get {
                return ResourceManager.GetString("eight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eighteen.
        /// </summary>
        public static string Eighteen {
            get {
                return ResourceManager.GetString("Eighteen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to eight hundred.
        /// </summary>
        public static string eighthundred {
            get {
                return ResourceManager.GetString("eighthundred", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eighty.
        /// </summary>
        public static string Eighty {
            get {
                return ResourceManager.GetString("Eighty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eleven.
        /// </summary>
        public static string Eleven {
            get {
                return ResourceManager.GetString("Eleven", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string Error1 {
            get {
                return ResourceManager.GetString("Error1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while deleting the information..
        /// </summary>
        public static string ErrorInDelete {
            get {
                return ResourceManager.GetString("ErrorInDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while editing the information..
        /// </summary>
        public static string ErrorInEdit {
            get {
                return ResourceManager.GetString("ErrorInEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while inserting the information..
        /// </summary>
        public static string ErrorInInsert {
            get {
                return ResourceManager.GetString("ErrorInInsert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while searching for information..
        /// </summary>
        public static string ErrorInSearch {
            get {
                return ResourceManager.GetString("ErrorInSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to December .
        /// </summary>
        public static string Esfand {
            get {
                return ResourceManager.GetString("Esfand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to example.
        /// </summary>
        public static string example {
            get {
                return ResourceManager.GetString("example", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to example.
        /// </summary>
        public static string example1 {
            get {
                return ResourceManager.GetString("example1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to January.
        /// </summary>
        public static string farvardin {
            get {
                return ResourceManager.GetString("farvardin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fifteen.
        /// </summary>
        public static string Fifteen {
            get {
                return ResourceManager.GetString("Fifteen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fifty.
        /// </summary>
        public static string Fifty {
            get {
                return ResourceManager.GetString("Fifty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please fill {0}.
        /// </summary>
        public static string FillField {
            get {
                return ResourceManager.GetString("FillField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please fill {0}.
        /// </summary>
        public static string FillField1 {
            get {
                return ResourceManager.GetString("FillField1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Five.
        /// </summary>
        public static string Five {
            get {
                return ResourceManager.GetString("Five", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to five hundred.
        /// </summary>
        public static string fivehundred {
            get {
                return ResourceManager.GetString("fivehundred", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to left.
        /// </summary>
        public static string Float {
            get {
                return ResourceManager.GetString("Float", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to left.
        /// </summary>
        public static string Float1 {
            get {
                return ResourceManager.GetString("Float1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forty.
        /// </summary>
        public static string Forty {
            get {
                return ResourceManager.GetString("Forty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Four.
        /// </summary>
        public static string Four {
            get {
                return ResourceManager.GetString("Four", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to four hundred.
        /// </summary>
        public static string fourhundred {
            get {
                return ResourceManager.GetString("fourhundred", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to fourteen.
        /// </summary>
        public static string fourteen {
            get {
                return ResourceManager.GetString("fourteen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Friday.
        /// </summary>
        public static string Friday {
            get {
                return ResourceManager.GetString("Friday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The requested information does not exist..
        /// </summary>
        public static string GetUnSuccessMessage {
            get {
                return ResourceManager.GetString("GetUnSuccessMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help.
        /// </summary>
        public static string Help {
            get {
                return ResourceManager.GetString("Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help.
        /// </summary>
        public static string Help1 {
            get {
                return ResourceManager.GetString("Help1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hour(s).
        /// </summary>
        public static string Hour {
            get {
                return ResourceManager.GetString("Hour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Information.
        /// </summary>
        public static string Information {
            get {
                return ResourceManager.GetString("Information", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Information.
        /// </summary>
        public static string Information1 {
            get {
                return ResourceManager.GetString("Information1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insert Document.
        /// </summary>
        public static string InsertDoc {
            get {
                return ResourceManager.GetString("InsertDoc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insert Document.
        /// </summary>
        public static string InsertDoc1 {
            get {
                return ResourceManager.GetString("InsertDoc1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insert Record.
        /// </summary>
        public static string InsertRecord {
            get {
                return ResourceManager.GetString("InsertRecord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insert Record.
        /// </summary>
        public static string InsertRecord1 {
            get {
                return ResourceManager.GetString("InsertRecord1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Information inserted successfully..
        /// </summary>
        public static string InsertSuccessMessage {
            get {
                return ResourceManager.GetString("InsertSuccessMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Right.
        /// </summary>
        public static string InversAligment {
            get {
                return ResourceManager.GetString("InversAligment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item.
        /// </summary>
        public static string Item {
            get {
                return ResourceManager.GetString("Item", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to March.
        /// </summary>
        public static string Khordad {
            get {
                return ResourceManager.GetString("Khordad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string Login1 {
            get {
                return ResourceManager.GetString("Login1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LogOut.
        /// </summary>
        public static string LogOut {
            get {
                return ResourceManager.GetString("LogOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to th.
        /// </summary>
        public static string M {
            get {
                return ResourceManager.GetString("M", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to main source.
        /// </summary>
        public static string mainsource {
            get {
                return ResourceManager.GetString("mainsource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to main source.
        /// </summary>
        public static string mainsource1 {
            get {
                return ResourceManager.GetString("mainsource1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Medium.
        /// </summary>
        public static string Medium {
            get {
                return ResourceManager.GetString("Medium", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to July.
        /// </summary>
        public static string Mehr {
            get {
                return ResourceManager.GetString("Mehr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Messaage Title.
        /// </summary>
        public static string MessaageTitle {
            get {
                return ResourceManager.GetString("MessaageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message.
        /// </summary>
        public static string Message {
            get {
                return ResourceManager.GetString("Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message.
        /// </summary>
        public static string Message1 {
            get {
                return ResourceManager.GetString("Message1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Million.
        /// </summary>
        public static string Million {
            get {
                return ResourceManager.GetString("Million", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minute(s).
        /// </summary>
        public static string Minute {
            get {
                return ResourceManager.GetString("Minute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monday.
        /// </summary>
        public static string Monday {
            get {
                return ResourceManager.GetString("Monday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to May.
        /// </summary>
        public static string Mordad {
            get {
                return ResourceManager.GetString("Mordad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The national code must be 10 characters.
        /// </summary>
        public static string NationalCodenotvalid {
            get {
                return ResourceManager.GetString("NationalCodenotvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Negative.
        /// </summary>
        public static string Negative {
            get {
                return ResourceManager.GetString("Negative", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nine.
        /// </summary>
        public static string Nine {
            get {
                return ResourceManager.GetString("Nine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to nine hundred.
        /// </summary>
        public static string ninehundred {
            get {
                return ResourceManager.GetString("ninehundred", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nineteen.
        /// </summary>
        public static string Nineteen {
            get {
                return ResourceManager.GetString("Nineteen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ninety.
        /// </summary>
        public static string ninety {
            get {
                return ResourceManager.GetString("ninety", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No key is provided for Table {0}.
        /// </summary>
        public static string Nokeyisprovided {
            get {
                return ResourceManager.GetString("Nokeyisprovided", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No key is provided for Table {0}.
        /// </summary>
        public static string Nokeyisprovided1 {
            get {
                return ResourceManager.GetString("Nokeyisprovided1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The number of input parameters is not equal to the number of keys ({0}).
        /// </summary>
        public static string NotValidinputparameterCount {
            get {
                return ResourceManager.GetString("NotValidinputparameterCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The number of input parameters is not equal to the number of keys ({0}).
        /// </summary>
        public static string NotValidinputparameterCount1 {
            get {
                return ResourceManager.GetString("NotValidinputparameterCount1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        public static string OK {
            get {
                return ResourceManager.GetString("OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        public static string OK1 {
            get {
                return ResourceManager.GetString("OK1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to One.
        /// </summary>
        public static string One {
            get {
                return ResourceManager.GetString("One", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operation Failed!.
        /// </summary>
        public static string OperationDoneFailed {
            get {
                return ResourceManager.GetString("OperationDoneFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operation Failed!.
        /// </summary>
        public static string OperationDoneFailed1 {
            get {
                return ResourceManager.GetString("OperationDoneFailed1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operation Succeed.
        /// </summary>
        public static string OperationDoneSucceed {
            get {
                return ResourceManager.GetString("OperationDoneSucceed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operation Succeed.
        /// </summary>
        public static string OperationDoneSucceed1 {
            get {
                return ResourceManager.GetString("OperationDoneSucceed1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to February.
        /// </summary>
        public static string OrDibehesht {
            get {
                return ResourceManager.GetString("OrDibehesht", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Original text.
        /// </summary>
        public static string Originaltext {
            get {
                return ResourceManager.GetString("Originaltext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Original text.
        /// </summary>
        public static string Originaltext1 {
            get {
                return ResourceManager.GetString("Originaltext1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to past.
        /// </summary>
        public static string past {
            get {
                return ResourceManager.GetString("past", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Point.
        /// </summary>
        public static string Point {
            get {
                return ResourceManager.GetString("Point", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Question.
        /// </summary>
        public static string Question {
            get {
                return ResourceManager.GetString("Question", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Question.
        /// </summary>
        public static string Question1 {
            get {
                return ResourceManager.GetString("Question1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to remained.
        /// </summary>
        public static string remained {
            get {
                return ResourceManager.GetString("remained", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saturday.
        /// </summary>
        public static string Saturday {
            get {
                return ResourceManager.GetString("Saturday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saturday.
        /// </summary>
        public static string Saturday1 {
            get {
                return ResourceManager.GetString("Saturday1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save and new.
        /// </summary>
        public static string SaveAndNew {
            get {
                return ResourceManager.GetString("SaveAndNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save and new language.
        /// </summary>
        public static string SaveAndNewLanguage {
            get {
                return ResourceManager.GetString("SaveAndNewLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save changes.
        /// </summary>
        public static string SaveChanges {
            get {
                return ResourceManager.GetString("SaveChanges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saving Data Failed.
        /// </summary>
        public static string SavingDataFailed {
            get {
                return ResourceManager.GetString("SavingDataFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saving Data Failed.
        /// </summary>
        public static string SavingDataFailed1 {
            get {
                return ResourceManager.GetString("SavingDataFailed1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Score.
        /// </summary>
        public static string Score {
            get {
                return ResourceManager.GetString("Score", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Score.
        /// </summary>
        public static string Score1 {
            get {
                return ResourceManager.GetString("Score1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Security.
        /// </summary>
        public static string Security {
            get {
                return ResourceManager.GetString("Security", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Security.
        /// </summary>
        public static string Security1 {
            get {
                return ResourceManager.GetString("Security1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Security Warning!.
        /// </summary>
        public static string SecurityWarning {
            get {
                return ResourceManager.GetString("SecurityWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Security Warning!.
        /// </summary>
        public static string SecurityWarning1 {
            get {
                return ResourceManager.GetString("SecurityWarning1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seven.
        /// </summary>
        public static string Seven {
            get {
                return ResourceManager.GetString("Seven", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to seven hundred.
        /// </summary>
        public static string sevenhundred {
            get {
                return ResourceManager.GetString("sevenhundred", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seventeen.
        /// </summary>
        public static string Seventeen {
            get {
                return ResourceManager.GetString("Seventeen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seventy.
        /// </summary>
        public static string Seventy {
            get {
                return ResourceManager.GetString("Seventy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to June.
        /// </summary>
        public static string Shahrivar {
            get {
                return ResourceManager.GetString("Shahrivar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Six.
        /// </summary>
        public static string Six {
            get {
                return ResourceManager.GetString("Six", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to six hundred.
        /// </summary>
        public static string sixhundred {
            get {
                return ResourceManager.GetString("sixhundred", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sixteen.
        /// </summary>
        public static string Sixteen {
            get {
                return ResourceManager.GetString("Sixteen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sixty.
        /// </summary>
        public static string sixty {
            get {
                return ResourceManager.GetString("sixty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Strong.
        /// </summary>
        public static string Strong {
            get {
                return ResourceManager.GetString("Strong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Succeed.
        /// </summary>
        public static string Succeed {
            get {
                return ResourceManager.GetString("Succeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Succeed.
        /// </summary>
        public static string Succeed1 {
            get {
                return ResourceManager.GetString("Succeed1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sunday.
        /// </summary>
        public static string Sunday {
            get {
                return ResourceManager.GetString("Sunday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to system.
        /// </summary>
        public static string system {
            get {
                return ResourceManager.GetString("system", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to system.
        /// </summary>
        public static string system1 {
            get {
                return ResourceManager.GetString("system1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ten.
        /// </summary>
        public static string ten {
            get {
                return ResourceManager.GetString("ten", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is no {0} to display.
        /// </summary>
        public static string There_is_no_item_to__display {
            get {
                return ResourceManager.GetString("There_is_no_item_to_ display", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thirteen.
        /// </summary>
        public static string Thirteen {
            get {
                return ResourceManager.GetString("Thirteen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to thirty.
        /// </summary>
        public static string thirty {
            get {
                return ResourceManager.GetString("thirty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This key has already been added.
        /// </summary>
        public static string Thiskeyhasalreadybeenadded {
            get {
                return ResourceManager.GetString("Thiskeyhasalreadybeenadded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thousand.
        /// </summary>
        public static string Thousand {
            get {
                return ResourceManager.GetString("Thousand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Three.
        /// </summary>
        public static string Three {
            get {
                return ResourceManager.GetString("Three", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to three hundred.
        /// </summary>
        public static string threehundred {
            get {
                return ResourceManager.GetString("threehundred", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thursday.
        /// </summary>
        public static string Thursday {
            get {
                return ResourceManager.GetString("Thursday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to April.
        /// </summary>
        public static string Tir {
            get {
                return ResourceManager.GetString("Tir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trillion.
        /// </summary>
        public static string Trillion {
            get {
                return ResourceManager.GetString("Trillion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tuesday.
        /// </summary>
        public static string Tuesday {
            get {
                return ResourceManager.GetString("Tuesday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to twelve.
        /// </summary>
        public static string twelve {
            get {
                return ResourceManager.GetString("twelve", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to twenty.
        /// </summary>
        public static string twenty {
            get {
                return ResourceManager.GetString("twenty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Two.
        /// </summary>
        public static string Two {
            get {
                return ResourceManager.GetString("Two", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to two hundred.
        /// </summary>
        public static string twohundred {
            get {
                return ResourceManager.GetString("twohundred", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unsucceed.
        /// </summary>
        public static string Unsucceed {
            get {
                return ResourceManager.GetString("Unsucceed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unsucceed.
        /// </summary>
        public static string Unsucceed1 {
            get {
                return ResourceManager.GetString("Unsucceed1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Document.
        /// </summary>
        public static string UpdateDoc {
            get {
                return ResourceManager.GetString("UpdateDoc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Document.
        /// </summary>
        public static string UpdateDoc1 {
            get {
                return ResourceManager.GetString("UpdateDoc1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Field.
        /// </summary>
        public static string UpdateField {
            get {
                return ResourceManager.GetString("UpdateField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Field.
        /// </summary>
        public static string UpdateField1 {
            get {
                return ResourceManager.GetString("UpdateField1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Information successfully updated.
        /// </summary>
        public static string UpdateSuccessMessage {
            get {
                return ResourceManager.GetString("UpdateSuccessMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Values.
        /// </summary>
        public static string Values {
            get {
                return ResourceManager.GetString("Values", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Values.
        /// </summary>
        public static string Values1 {
            get {
                return ResourceManager.GetString("Values1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VeryStrong.
        /// </summary>
        public static string VeryStrong {
            get {
                return ResourceManager.GetString("VeryStrong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VeryWeak.
        /// </summary>
        public static string VeryWeak {
            get {
                return ResourceManager.GetString("VeryWeak", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning.
        /// </summary>
        public static string Warning {
            get {
                return ResourceManager.GetString("Warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning.
        /// </summary>
        public static string Warning1 {
            get {
                return ResourceManager.GetString("Warning1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weak.
        /// </summary>
        public static string Weak {
            get {
                return ResourceManager.GetString("Weak", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wednesday.
        /// </summary>
        public static string Wednesday {
            get {
                return ResourceManager.GetString("Wednesday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to zero.
        /// </summary>
        public static string zero {
            get {
                return ResourceManager.GetString("zero", resourceCulture);
            }
        }
    }
}
